apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - name: "udp"
    protocol: UDP
    port: 30300
    targetPort: 30300
    nodePort: 30300
  selector:
    k8s-app: jitsi



